package com.ace.notify;

public enum NotificationType {
	ISSUE_SUCCESS,
	ISSUE_FAILED,
	ISSUE_FAILED_BATCH,
	CONSISTENCY_CHECK_FAILED,
	COUPON_ISSUANCE_ALL_COMPLETED,
	CONSISTENCY_BATCH_STARTED,
	CONSISTENCY_STEP_STARTED,
	CONSISTENCY_STEP_COMPLETED,
	CONSISTENCY_BATCH_COMPLETED,
	SCHEDULER_STARTED,
	SCHEDULER_COMPLETED
}
