apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://ace-prometheus:9090
    isDefault: true
    editable: false

  - name: Ace MySQL
    type: mysql
    uid: ace-mysql
    access: proxy
    url: ace-mysql:3306
    user: root
    jsonData:
      database: ${MYSQL_DATABASE}
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
    secureJsonData:
      password: ${MYSQL_ROOT_PASSWORD}
    editable: false
